### ISSUE TITLE
Consider removing RP1.1.2.1

### ISSUE THREAD

**Issue by SteveBranton54** [Free-moN-net/Website#13]
RP1.1.2.1 says "A 24 inch width is recommended for ease of transportation and continuity with other modules. Any deviation from this recommended width would result in cosmetic misalignment of the fascia with other modules." 
This is simply outdated. Cosmetic misalignment of the fascia with other modules does not seem to concern the community. And it will get worse with the new "minimum 4 inches from track center to fascia" language.

**Comment by SteveBranton54** [comment]
Suggest replacing with this RP "There is no maximum width of an endplate, however, consider the practical limits of the 
width you can transport in your vehicle when choosing an endplate width. Endplate widths of 12”, 18” and 24” are common in the community and other widths are in use.

**Comment by Skallyline** [comment]
I like Steve's working on the RP

**Comment by Skallyline** [comment]
Our discussion 6/6 was to remove the RP and address it in the FAQ.

**Comment by pabender** [comment]
Closed by #20
