### ISSUE TITLE
Correct the paranthetical comment in S2.4 -- maximum grade

### ISSUE THREAD

**Issue by SteveBranton54** [Free-moN-net/Website#14]
A 2% grade is 2" per 100", 1" per 50" or 1/4" per 12 1/2". The current language says "(1/4 inch per foot)" This results in a grade greater than 2%. :-(

**Comment by Skallyline** [comment]
Easy fix, let's make it happen.

**Comment by Skallyline** [comment]
Resolved 6/6 to update the language with Steve's verbiage.

**Comment by pabender** [comment]
Closed by #20
