### ISSUE TITLE
Codify Track vs Accessory Bus Usage

### ISSUE THREAD

**Issue by SteveBranton54** [Free-moN-net/Website#16]
Bob.Luzenski wrote: As for the track bus change, removal of RP3.3.4.1 is necessary to accomplish your stated goal, but not sufficient. Both the track and accessory bus sections leave the use of each bus implied by the name. If the intent is restrict use of the track bus to only be used to connect power to the rails, you need a requirement (S section) that actually says that. As it stands even with the change proposed, the use of the bus is only implied, not stated explicitly.

Suggest we remove  RP3.3.4.1 as planned and then implement Bob's suggested standard in a subsequent revision.

**Comment by pabender** [comment]
This is actually addressed by issue #7.

**Comment by pabender** [comment]
This is included in #7
