### ISSUE TITLE
Module height for non-grade modules.

### ISSUE THREAD

**Issue by pabender** [Free-moN-net/Website#2]
The Free-moN standards allow modules with grades to change layout elevation at the endplate with a maximum height of 62” in .75” increments.  

This standard was intended to apply to all modules, but ambiguity in the language allows an interpretation by which modules without grades are not required to be set at any height above 51”.

**Comment by willcgage** [comment]
Are we under the thought of decreasing the 12" change allowance and setting it to something like 4" to 6"?  50" - 56"

**Comment by pabender** [comment]
I am not opposed to reducing the maximum height.  

Personally, i think it is more likely that someone will build a module that goes up a few inches than someone might build a full scale Tehachapi loop.

In practical terms, i think that means the layout goes up a few inches, stays there for some distance, and then goes back down.

Of course, this issue wasn’t intended to address the maximum height, but it is something to consider here and with issues #3 and #12.

**Comment by Skallyline** [comment]
Looking at how to keep shows as smooth as possible, I think this clause should be deleted all together. The grade option allows module owners to move up and down as much as they want within their own modules. The module ends should be a nominal 50". I don't want to confuse new module builders.

**Comment by pabender** [comment]
I actually think the best way to handle this to do two things:
1) removing the ambiguity in the current language.
2) add an RP to the part of the leg standards that says “to account for modules with grades, legs shall have adjustment between -1 inch and +n inches” where n is some whole number greater than 1 and no larger than 13.  

The RP adds to the flexibility of modules that implement it, but doesn’t overly complicate construction.  For most leg systems, it just means using longer carriage bolts for levelers.  Also, for layout planners, you just need to ask the question “does your module comply with RP x.y.z”

**Comment by Skallyline** [comment]
Here was the proposed amendment from this morning:
"S1.2.4 Nominal height of the railhead from the floor shall be 50 inches at the endplates."

No change to grades up, this allows for grades to go downhill, and it ensures all modules will align at shows.

**Comment by djennex** [comment]
I don't understand the grade specs at all.
No discussion concerning the end plates has taken place.
Should end plates on grade modules or sets of modules be plumb but at different heights above the ground plane (perpendicular to ground plane - requiring the top edge to be beveled), perpendicular to the rising or declining track, level (same height from ground plane - then track not attached to the top of the end plate) ?

**Comment by pabender** [comment]
> I don't understand the grade specs at all.
> No discussion concerning the end plates has taken place.
> Should end plates on grade modules or sets of modules be plumb but at different heights above the ground plane (perpendicular to ground plane - requiring the top edge to be beveled), perpendicular to the rising or declining track, level (same height from ground plane - then track not attached to the top of the end plate) ?

If you look at S2.6, http://free-mon.net/standard.html#2.6, it states that “ All track crossing the endplate shall be perpendicular, straight, and level for at least 4 inches from the outside face of the endplate”.

This is true regardless of whether or not the module has a grade.  

That said, I think what you are really asking about is a multi-section module where the grade continues through several sections.  At the section joints ( which are internal joints to the module) the grade can continue right across the ends of the sections.

if that doesn’t answer your question, I can draw you a sketch to help explain.

**Comment by djennex** [comment]
Thanks Paul for the prompt attention!
I am familiar with #2.6. My 16 ft module under construction as four 4ft sections are compliant at all ends for main track but contoured upward and beveled to match the grades. This allows the soldered ties to be attached to the end plates for precise alignment.
Then the end plates are aligned using bronze "table leaf pins.
BTW. Did I deal with you when I did the buying for the RC plane dept. as a fairly large hobby shop?

**Comment by pabender** [comment]
closed by #21

**Comment by ednadolski-ix** [comment]
> Personally, i think it is more likely that someone will build a module that goes up a few inches than someone might build a full scale Tehachapi loop.

Interesting, I've been mulling over exactly that.  But it is a considerable practical challenge, to say the least.

https://i.imgur.com/ZqHFrog.jpg

As drawn, the total elevation change would be over 18 inches -- considerably above what the standard would allow.

Ed
