### ISSUE TITLE
Double track

### ISSUE THREAD

**Issue by pabender** [Free-moN-net/Website#4]
There is a defacto double track standard of 1.125” used by most groups and individuals.  Should this be codified as a standard or RP.

**Comment by SteveBranton54** [comment]
[Double track question.docx](https://github.com/Free-moN-net/Website/files/7833759/Double.track.question.docx)

**Comment by Skallyline** [comment]
I used to be a single track purist, but I am very open to the 1.125" double track RP as long as we have a clause that requires the double track module owner (or owners) to provide the Double to Single Transition Module for continuity at shows. The reason for this is the difficulty people have in maintaining the 1.125" spacing. Evanston proved that (we had to resolder several tracks to get them into gauge).

**Comment by willcgage** [comment]
are we ready to publish the changes?

**Comment by pabender** [comment]
Closed by merging #9
